### ISSUE TITLE
Question + ckpt names are wrong

### ISSUE THREAD

**Issue by jwyndreee** [ccc870206/3D-PL#3]
Dear authors, thank you for your great work!

I noticed that the folder names in your gdrive link are set wrong (the single image folder contains the checkpoint for the stereo model and vice versa xD)

One question, is there any reason why you did not use median scaling during evaluation whereas former work(e.g. S2R-Depthnet) have done so?

Thanks,

**Comment by ccc870206** [comment]
Hi, thank you for finding the folder name issue! I have already put the weights in the correct folder.

About the question related to median scaling, since the classical baseline (e.g. T2net, GASDA) we compare to don't use the median scaling, we adopt the same setting for a fair comparison.
